begin;
-- =========================================================
-- B · 상품·채소 초기 데이터 (seed)
-- 원본: src/data/mock/vegetables.ts, products.ts (변환기로 자동 생성)
-- 2026-10-08 상품 16개 → 67개, 채소 12종 → 21종 확장. 기존 상품 ID는 그대로예요.
-- 채소 21개, 상품 67개
-- 농가 이름·가격·보관법 문구는 시연용 가상 데이터입니다.
-- 여러 번 실행해도 중복되지 않도록 id 기준으로 덮어써요(upsert).
-- 순서: 채소 먼저 → 상품 (상품이 채소를 가리키기 때문)
-- =========================================================

insert into public.vegetables (id, name, category, description, storage_guide, prep_guide, season, image_path) values
  ('carrot', '당근', 'root', '달큰하고 아삭한 뿌리채소예요. 생으로 먹어도, 볶거나 쪄도 맛있어요.', '흙을 털지 말고 신문지에 싸서 냉장고 채소칸에 세워 보관하세요.', '껍질 가까이에 영양이 많아서 깨끗이 씻은 뒤 얇게만 벗기세요.', '9~12월', 'vegetables/carrot.jpg'),
  ('apple', '사과', 'fruit', '새콤달콤한 과일이에요. 그대로 먹거나 샐러드, 잼으로 즐겨요.', '하나씩 비닐에 싸서 냉장 보관하세요. 다른 과일과 떨어뜨려 두면 좋아요.', '흐르는 물에 문질러 씻고, 흠집 난 부분만 도려내면 돼요.', '9~11월', 'vegetables/apple.jpg'),
  ('shiitake', '표고버섯', 'mushroom', '향이 진하고 쫄깃한 버섯이에요. 국물 요리와 볶음에 잘 어울려요.', '물에 씻지 말고 키친타월에 싸서 냉장 보관하세요.', '밑동을 떼고 젖은 행주로 겉을 살살 닦아 주세요.', '3~5월, 9~11월', 'vegetables/shiitake.jpg'),
  ('cabbage', '양배추', 'leaf', '아삭하고 단맛이 나는 잎채소예요. 샐러드, 볶음, 쌈으로 먹어요.', '심을 도려내고 젖은 키친타월을 채운 뒤 랩으로 싸서 냉장 보관하세요.', '겉잎 한두 장을 떼고 한 장씩 흐르는 물에 씻어 주세요.', '3~6월', 'vegetables/cabbage.jpg'),
  ('paprika', '파프리카', 'fruit_veg', '색이 화사하고 단맛이 나는 열매채소예요. 생으로도 볶아서도 좋아요.', '물기를 닦고 비닐에 담아 냉장 보관하세요.', '꼭지와 씨를 빼고 흐르는 물에 씻어 주세요.', '4~10월', 'vegetables/paprika.jpg'),
  ('onion', '양파', 'root', '볶으면 단맛이 살아나는 채소예요. 거의 모든 요리의 기본 재료예요.', '망에 담아 바람이 잘 통하고 그늘진 곳에 걸어 두세요.', '위아래를 자르고 겉껍질을 벗긴 뒤, 차갑게 해서 썰면 눈이 덜 매워요.', '4~6월', 'vegetables/onion.jpg'),
  ('potato', '감자', 'root', '포슬포슬하고 담백한 뿌리채소예요. 찌거나 굽거나 볶아서 다양하게 즐겨요.', '빛이 들지 않는 서늘한 곳에 두세요. 사과를 한두 개 함께 두면 싹이 덜 나요.', '싹이나 초록색으로 변한 부분은 독성이 있으니 넉넉히 도려내고 조리하세요.', '6~9월', 'vegetables/potato-small.jpg'),
  ('sweet-potato', '고구마', 'root', '구우면 꿀처럼 달콤해지는 뿌리채소예요. 간식으로도 식사로도 좋아요.', '냉장 보관하면 쉽게 상해요. 신문지에 싸서 13~15도 정도 서늘한 실온에 두세요.', '흙을 씻어 내고 껍질째 굽거나 쪄 드세요. 자른 면은 물에 담가 두면 덜 변해요.', '9~11월', 'vegetables/sweet-potato.jpg'),
  ('tomato', '토마토', 'fruit_veg', '새콤하고 감칠맛이 나는 열매채소예요. 익혀 먹으면 영양 흡수가 더 좋아요.', '덜 익었으면 실온에서 후숙하고, 잘 익으면 꼭지를 아래로 해서 냉장 보관하세요.', '꼭지를 떼고 씻어요. 껍질을 벗기려면 열십자로 칼집을 내 끓는 물에 살짝 데치세요.', '5~8월', 'vegetables/tomato.jpg'),
  ('cucumber', '오이', 'fruit_veg', '아삭하고 시원한 열매채소예요. 무침, 냉국, 피클로 즐겨요.', '물기를 닦고 키친타월에 싸서 꼭지가 위로 가게 세워 냉장 보관하세요.', '굵은 소금으로 겉을 문질러 씻으면 가시가 정리되고 색이 선명해져요.', '4~8월', 'vegetables/cucumber.jpg'),
  ('green-onion', '대파', 'seasoning', '국, 볶음, 무침 어디에나 들어가는 기본 양념채소예요.', '흰 부분과 초록 부분을 나눠 썰어 밀폐 용기에 담아 냉장·냉동 보관하세요.', '뿌리를 자르고 겉껍질 한 겹을 벗긴 뒤 흐르는 물에 씻어 주세요.', '11~2월', 'vegetables/green-onion.jpg'),
  ('spinach', '시금치', 'leaf', '단맛이 도는 잎채소예요. 나물, 국, 볶음으로 두루 써요.', '젖은 키친타월에 싸서 뿌리가 아래로 가게 세워 냉장 보관하세요.', '뿌리 쪽 흙을 깨끗이 씻고, 끓는 소금물에 30초 정도만 데치세요.', '11~3월', 'vegetables/spinach.jpg'),
  ('radish', '무', 'root', '시원하고 단맛이 나는 뿌리채소예요. 국, 조림, 깍두기에 꼭 들어가요.', '잎을 잘라 내고 신문지에 싸서 서늘한 곳이나 냉장고에 세워 두세요.', '흙을 씻고 껍질은 얇게 벗겨요. 윗부분은 달고 아랫부분은 매워요.', '10~12월', 'vegetables/radish-bent.jpg'),
  ('broccoli', '브로콜리', 'leaf', '작은 꽃송이가 모인 채소예요. 데쳐서 샐러드나 볶음으로 먹어요.', '비닐에 느슨하게 담아 꽃송이가 위로 가게 냉장 보관하세요.', '작은 송이로 나눠 거꾸로 물에 담가 흔들어 씻은 뒤 1분 정도만 데쳐요.', '11~3월', 'vegetables/broccoli-small.jpg'),
  ('napa-cabbage', '배추', 'leaf', '김치와 국에 빠지지 않는 잎채소예요. 속잎은 고소하고 달아요.', '겉잎을 떼지 말고 신문지에 싸서 서늘한 곳에 세워 두세요.', '밑동을 자르고 한 장씩 떼어 흐르는 물에 씻어요.', '10~12월', 'vegetables/napa-cabbage-small.jpg'),
  ('aehobak', '애호박', 'fruit_veg', '연하고 달큰한 열매채소예요. 전, 볶음, 된장찌개에 두루 써요.', '물기를 닦고 한 개씩 랩으로 싸서 냉장고 채소칸에 세워 두세요.', '꼭지를 자르고 씻은 뒤 껍질째 썰어요. 씨가 크면 숟가락으로 긁어내세요.', '6~8월', 'vegetables/aehobak-small.jpg'),
  ('eggplant', '가지', 'fruit_veg', '부드럽고 기름을 잘 머금는 열매채소예요. 나물, 볶음, 구이로 즐겨요.', '너무 차가우면 금방 물러요. 키친타월에 싸서 냉장고 채소칸에 넣고 빨리 드세요.', '꼭지를 자르고 썬 뒤 바로 조리하세요. 미리 썰면 색이 변해요.', '6~9월', 'vegetables/eggplant-small.jpg'),
  ('sweet-pumpkin', '단호박', 'fruit_veg', '포슬포슬하고 달콤한 호박이에요. 찌거나 구워서 간식으로 먹어요.', '통째로는 바람이 잘 통하는 실온에, 자른 것은 씨를 빼고 랩으로 싸서 냉장 보관하세요.', '전자레인지에 2~3분 돌리면 단단한 껍질이 잘 썰려요.', '7~9월', 'vegetables/danhobak-small.jpg'),
  ('king-oyster', '새송이버섯', 'mushroom', '대가 굵고 쫄깃한 버섯이에요. 구이, 볶음, 장조림에 잘 어울려요.', '물에 씻지 말고 키친타월에 싸서 냉장 보관하세요.', '밑동만 살짝 자르고 젖은 행주로 닦아 쓰세요.', '사계절', 'vegetables/king-oyster-small.jpg'),
  ('mandarin', '귤', 'fruit', '새콤달콤하고 껍질이 잘 까지는 겨울 과일이에요.', '서로 닿지 않게 펼쳐서 서늘한 곳에 두고, 무른 귤은 바로 골라내세요.', '흐르는 물에 씻어 그대로 까서 드세요. 껍질은 말려 차로 마셔도 좋아요.', '11~2월', 'vegetables/mandarin-small.jpg'),
  ('chili', '고추', 'seasoning', '매콤한 맛을 더하는 양념채소예요. 찌개, 볶음, 장아찌에 써요.', '꼭지를 떼지 말고 키친타월에 싸서 냉장 보관하거나, 썰어서 냉동하세요.', '꼭지를 떼고 씻은 뒤, 덜 맵게 하려면 반으로 갈라 씨를 빼요.', '6~9월', 'vegetables/chili-small.jpg')
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  storage_guide = excluded.storage_guide,
  prep_guide = excluded.prep_guide,
  season = excluded.season,
  image_path = excluded.image_path;

insert into public.products (id, vegetable_id, name, description, price, original_price, unit, ugly_reason, condition_note, farm_name, farm_region, farm_story, image_path, is_seasonal, is_featured, is_active) values
  ('carrot-bent-1kg', 'carrot', '못난이 당근 1kg', '달고 아삭한 해남 당근이에요. 크기가 고르지 않고 조금 휘어서 일반 유통에서 제외됐어요.', 2900, 4800, '1kg (5~8개)', 'bent', '모양이 조금 휘었을 뿐, 당도와 식감은 정상품과 같아요.', '해남 김씨농장', '전라남도 해남', '황토밭에서 당근을 키우고 있어요. 모양이 달라도 정성은 똑같습니다.', 'products/carrot.jpg', true, true, true),
  ('apple-scratched-2kg', 'apple', '흠과 사과 2kg', '바람에 흔들려 생긴 흠집 때문에 B급이 된 사과예요. 새콤달콤한 맛은 그대로예요.', 12900, 19800, '2kg (7~9개)', 'scratched', '껍질에 작은 흠집이 있지만 과육은 멀쩡해요.', '청송 사과농원', '경상북도 청송', '일교차가 큰 산골에서 사과를 키워 단맛이 진해요.', 'products/apple.jpg', true, true, true),
  ('shiitake-irregular-500g', 'shiitake', 'B급 표고버섯 500g', '크기가 고르지 않아 선별에서 빠진 표고버섯이에요. 국물 요리와 볶음에 좋아요.', 6900, 9900, '500g', 'irregular', '갓 크기가 제각각이지만 향과 식감은 좋아요.', '장흥 버섯농가', '전라남도 장흥', '참나무 원목에서 버섯을 천천히 키우고 있어요.', 'products/shiitake.jpg', false, true, true),
  ('cabbage-small-1ea', 'cabbage', '꼬마 양배추 1통', '크기가 작아 규격에서 빠진 양배추예요. 1인 가구가 한 번에 쓰기 딱 좋아요.', 1900, 3500, '1통', 'small', '일반 양배추보다 작지만 속이 꽉 찼어요.', '평창 고랭지농장', '강원도 평창', '서늘한 고랭지에서 자라 아삭함이 살아 있어요.', 'products/cabbage.jpg', false, true, true),
  ('paprika-irregular-4ea', 'paprika', '못난이 파프리카 4입', '모양이 고르지 않은 파프리카 4가지 색 모음이에요. 샐러드와 볶음에 좋아요.', 4900, 7900, '4입', 'irregular', '모양이 삐뚤지만 색과 단맛은 그대로예요.', '영양 파프리카농장', '경상북도 영양', '빨강, 노랑, 주황, 초록 파프리카를 함께 키워요.', 'products/paprika.jpg', false, false, true),
  ('onion-small-2kg', 'onion', '꼬마 양파 2kg', '알이 작아 규격 외로 분류된 양파예요. 볶음, 카레, 장아찌에 쓰기 좋아요.', 3900, 6700, '2kg', 'small', '알이 작아 손질이 조금 번거롭지만 맛은 똑같아요.', '무안 양파밭', '전라남도 무안', '바닷바람이 부는 황토밭에서 양파를 키워요.', 'products/onion.jpg', true, false, true),
  ('potato-small-3kg', 'potato', '꼬마 감자 3kg', '크기가 작아 선별에서 빠진 감자예요. 조림, 버터구이, 통감자구이에 딱이에요.', 5900, 9800, '3kg', 'small', '알이 작아 껍질째 통으로 조리하기 좋아요.', '강릉 감자밭', '강원도 강릉', '서늘한 고랭지 바람을 맞고 자라 포슬포슬해요.', 'products/potato-small.jpg', true, false, true),
  ('potato-scratched-2kg', 'potato', '흠집 감자 2kg', '수확할 때 생긴 흠집 때문에 B급이 된 감자예요. 껍질만 벗기면 정상품과 같아요.', 4500, 6900, '2kg', 'scratched', '캐는 과정에서 생긴 겉 흠집이 있지만 속은 멀쩡해요.', '평창 고랭지농장', '강원도 평창', '양배추와 함께 감자도 기르고 있어요.', 'products/potato-scratched.jpg', true, false, true),
  ('sweet-potato-bent-2kg', 'sweet-potato', '못난이 꿀고구마 2kg', '모양이 고르지 않아 상자에 예쁘게 담기 어려운 꿀고구마예요. 맛은 그대로예요.', 7900, 12900, '2kg', 'bent', '모양이 휘고 길쭉하지만 구우면 꿀처럼 달아요.', '해남 황토고구마', '전라남도 해남', '황토밭에서 키워 당도가 높은 꿀고구마예요.', 'products/sweet-potato.jpg', true, false, true),
  ('sweet-potato-small-1-5kg', 'sweet-potato', '한입 고구마 1.5kg', '작아서 규격에서 빠진 고구마예요. 간식으로 하나씩 꺼내 먹기 편해요.', 5500, 8500, '1.5kg', 'small', '한입 크기로 작아서 에어프라이어에 굽기 좋아요.', '여주 고구마농원', '경기도 여주', '모래가 섞인 땅에서 키워 껍질이 매끈해요.', 'products/sweet-potato-small.jpg', true, false, true),
  ('tomato-irregular-1kg', 'tomato', '못난이 토마토 1kg', '모양이 고르지 않은 토마토예요. 소스, 수프, 샐러드에 쓰기 좋아요.', 4900, 7900, '1kg', 'irregular', '크기와 모양이 제각각이지만 완숙으로 수확했어요.', '부여 토마토하우스', '충청남도 부여', '줄기에서 충분히 익혀 따서 감칠맛이 진해요.', 'products/tomato.jpg', true, false, true),
  ('cucumber-bent-5ea', 'cucumber', '휜 오이 5입', '곧게 자라지 않아 B급이 된 오이예요. 무침이나 오이냉국으로 드셔 보세요.', 2900, 4500, '5입', 'bent', '활처럼 휘었지만 아삭함은 그대로예요.', '천안 오이농장', '충청남도 천안', '매일 아침 수확해서 바로 보내 드려요.', 'products/cucumber.jpg', true, false, true),
  ('green-onion-small-1bunch', 'green-onion', '짧은 대파 1단', '길이가 짧은 대파예요. 썰어서 냉동해 두면 국과 볶음에 바로 쓸 수 있어요.', 1900, 3200, '1단', 'small', '길이가 짧아 규격에서 빠졌지만 향은 진해요.', '진도 대파밭', '전라남도 진도', '겨울 바닷바람을 맞고 자라 단맛이 나요.', 'products/green-onion.jpg', false, false, true),
  ('spinach-small-500g', 'spinach', '잎 작은 시금치 500g', '잎 크기가 작아 선별에서 빠진 시금치예요. 나물이나 된장국에 좋아요.', 2500, 3900, '500g', 'small', '잎이 작지만 연하고 단맛이 좋아요.', '남해 섬시금치', '경상남도 남해', '바닷바람을 맞고 자라 뿌리 쪽이 달아요.', 'products/spinach.jpg', false, false, true),
  ('carrot-irregular-3kg', 'carrot', '굵기 제각각 당근 3kg', '굵기가 고르지 않은 당근을 넉넉히 담았어요. 당근주스나 라페를 만들기 좋아요.', 6900, 11500, '3kg', 'irregular', '굵기가 들쭉날쭉하지만 주스나 요리에는 문제없어요.', '제주 구좌당근', '제주특별자치도 구좌', '화산토에서 키워 단단하고 달아요.', 'products/carrot-bulk.jpg', true, false, true),
  ('apple-small-3kg', 'apple', '소과 사과 3kg', '크기가 작아 선물용에서 빠진 사과예요. 도시락 과일로 하나씩 챙기기 좋아요.', 15900, 25800, '3kg (14~18개)', 'small', '크기가 작아 한 번에 먹기 좋은 사이즈예요.', '영주 사과마을', '경상북도 영주', '소백산 아래 일교차가 큰 곳에서 키웠어요.', 'products/apple-small.jpg', true, false, true),
  ('carrot-scratched-2kg', 'carrot', '흠집 당근 2kg', '겉에 작은 흠집이 생겨 B급이 된 당근이에요. 껍질을 얇게 벗기면 정상품과 같아요.', 3900, 6400, '2kg', 'scratched', '캘 때 생긴 겉 흠집이 있지만 속은 단단해요.', '해남 김씨농장', '전라남도 해남', '황토밭에서 당근을 키우고 있어요. 모양이 달라도 정성은 똑같습니다.', 'products/carrot-scratched.jpg', true, false, true),
  ('onion-scratched-3kg', 'onion', '껍질 벗겨진 양파 3kg', '수확하면서 겉껍질이 벗겨진 양파예요. 손질이 오히려 더 편해요.', 4500, 7500, '3kg', 'scratched', '겉껍질이 벗겨져 보기만 덜 예뻐요. 속은 단단해요.', '무안 양파밭', '전라남도 무안', '바닷바람이 부는 황토밭에서 양파를 키워요.', 'products/onion-scratched.jpg', true, false, true),
  ('onion-irregular-5kg', 'onion', '모양 제각각 양파 5kg', '모양과 크기가 고르지 않은 양파를 넉넉히 담았어요. 자주 요리하는 집에 좋아요.', 6900, 11900, '5kg', 'irregular', '크기와 모양이 섞여 있어요. 큰 건 볶음, 작은 건 장아찌로 써 보세요.', '창녕 양파마을', '경상남도 창녕', '낙동강 옆 기름진 땅에서 양파를 키워요.', 'products/onion-irregular.jpg', true, false, true),
  ('potato-irregular-5kg', 'potato', '울퉁불퉁 감자 5kg', '모양이 울퉁불퉁해서 선별에서 빠진 감자예요. 으깨거나 국에 넣기 좋아요.', 8900, 14500, '5kg', 'irregular', '울퉁불퉁하고 크기가 섞여 있지만 포슬포슬해요.', '강릉 감자밭', '강원도 강릉', '서늘한 고랭지 바람을 맞고 자라 포슬포슬해요.', 'products/potato-irregular.jpg', true, false, true),
  ('sweet-potato-scratched-3kg', 'sweet-potato', '흠집 꿀고구마 3kg', '수확할 때 껍질에 흠집이 생긴 꿀고구마예요. 구우면 꿀처럼 달아요.', 8500, 13900, '3kg', 'scratched', '캘 때 생긴 흠집이 있어요. 흠집 부분만 도려내면 돼요.', '해남 황토고구마', '전라남도 해남', '황토밭에서 키워 당도가 높은 꿀고구마예요.', 'products/sweet-potato-scratched.jpg', true, false, true),
  ('radish-bent-1ea', 'radish', '휜 무 1개', '자라면서 휘어진 무예요. 국이나 조림에 넣으면 모양은 상관없어요.', 1500, 2800, '1개 (약 1.5kg)', 'bent', '휘어서 자르기가 조금 불편하지만 시원하고 달아요.', '고창 황토무밭', '전라북도 고창', '황토밭에서 자라 단단하고 물이 많아요.', 'products/radish-bent.jpg', true, false, true),
  ('radish-scratched-2ea', 'radish', '흠집 무 2개', '캘 때 겉에 흠집이 생긴 무예요. 깍두기나 무생채를 넉넉히 만들 수 있어요.', 2500, 4600, '2개 (약 3kg)', 'scratched', '겉에 흠집이 있어요. 껍질만 벗기면 속은 하얗고 깨끗해요.', '평창 고랭지농장', '강원도 평창', '서늘한 고랭지에서 자라 아삭함이 살아 있어요.', 'products/radish-scratched.jpg', true, false, true),
  ('radish-irregular-1ea', 'radish', '다리 무 1개', '뿌리가 갈라져 ''다리 무''가 된 무예요. 어묵탕이나 소고기뭇국에 좋아요.', 1300, 2800, '1개 (약 1.2kg)', 'irregular', '뿌리가 두 갈래로 갈라졌어요. 맛은 똑같이 시원해요.', '제주 구좌당근', '제주특별자치도 구좌', '화산토에서 키워 단단하고 달아요.', 'products/radish-irregular.jpg', true, false, true),
  ('cabbage-scratched-1ea', 'cabbage', '겉잎 상처 양배추 1통', '겉잎에 생긴 상처 때문에 B급이 된 양배추예요. 속은 단단하고 달아요.', 2500, 4200, '1통 (약 2kg)', 'scratched', '겉잎 몇 장에 상처가 있어요. 한두 장만 떼면 속은 깨끗해요.', '평창 고랭지농장', '강원도 평창', '서늘한 고랭지에서 자라 아삭함이 살아 있어요.', 'products/cabbage-scratched.jpg', false, false, true),
  ('cabbage-irregular-2ea', 'cabbage', '모양 제각각 양배추 2통', '모양이 둥글지 않아 규격에서 빠진 양배추 2통이에요. 쌈, 샐러드, 볶음에 좋아요.', 3900, 6900, '2통', 'irregular', '동그랗지 않고 납작하거나 길쭉해요.', '제주 한림밭', '제주특별자치도 한림', '바닷바람을 맞고 자라 잎이 두툼해요.', 'products/cabbage-irregular.jpg', true, false, true),
  ('spinach-irregular-1kg', 'spinach', '잎 모양 제각각 시금치 1kg', '잎 모양이 고르지 않은 시금치를 넉넉히 담았어요. 나물을 많이 무칠 때 좋아요.', 4500, 6900, '1kg', 'irregular', '잎 크기와 모양이 섞여 있지만 연하고 달아요.', '남해 섬시금치', '경상남도 남해', '바닷바람을 맞고 자라 뿌리 쪽이 달아요.', 'products/spinach-irregular.jpg', false, false, true),
  ('spinach-scratched-500g', 'spinach', '잎끝 상처 시금치 500g', '수확하면서 잎 끝이 찢어진 시금치예요. 된장국이나 볶음에 바로 넣어 보세요.', 2200, 3900, '500g', 'scratched', '잎 끝 몇 군데가 찢어졌어요. 데치면 티가 안 나요.', '남해 섬시금치', '경상남도 남해', '바닷바람을 맞고 자라 뿌리 쪽이 달아요.', 'products/spinach-scratched.jpg', false, false, true),
  ('broccoli-small-3ea', 'broccoli', '꼬마 브로콜리 3송이', '크기가 작아 규격에서 빠진 브로콜리예요. 한 송이씩 데쳐 먹기 좋아요.', 3900, 6500, '3송이', 'small', '송이가 작지만 단단하고 색이 진해요.', '제주 한림밭', '제주특별자치도 한림', '바닷바람을 맞고 자라 잎이 두툼해요.', 'products/broccoli-small.jpg', true, false, true),
  ('broccoli-irregular-2ea', 'broccoli', '모양 제각각 브로콜리 2송이', '모양이 고르지 않은 브로콜리예요. 작은 송이로 나누면 모양은 상관없어요.', 3500, 5800, '2송이', 'irregular', '송이 모양이 한쪽으로 쏠려 있지만 맛은 그대로예요.', '평창 고랭지농장', '강원도 평창', '서늘한 고랭지에서 자라 아삭함이 살아 있어요.', 'products/broccoli-irregular.jpg', true, false, true),
  ('broccoli-scratched-2ea', 'broccoli', '겉송이 멍 브로콜리 2송이', '겉 송이에 작은 멍이 든 브로콜리예요. 볶음이나 수프에 쓰기 좋아요.', 2900, 5800, '2송이', 'scratched', '겉 송이 몇 개에 멍이 있어요. 그 부분만 떼고 드세요.', '제주 한림밭', '제주특별자치도 한림', '바닷바람을 맞고 자라 잎이 두툼해요.', 'products/broccoli-scratched.jpg', true, false, true),
  ('napa-cabbage-small-2ea', 'napa-cabbage', '알배기 배추 2통', '크기가 작아 김장용에서 빠진 배추예요. 쌈, 배춧국, 겉절이에 좋아요.', 3900, 6500, '2통', 'small', '작은 크기의 알배기라 쌈이나 국에 바로 쓰기 좋아요.', '해남 땅끝배추', '전라남도 해남', '겨울에도 따뜻한 땅끝에서 배추를 키워요.', 'products/napa-cabbage-small.jpg', true, false, true),
  ('napa-cabbage-scratched-1ea', 'napa-cabbage', '겉잎 상처 배추 1통', '겉잎에 상처가 있어 B급이 된 배추예요. 김치를 담그면 정상품과 같아요.', 2900, 5500, '1통 (약 3kg)', 'scratched', '겉잎에 상처와 구멍이 있어요. 겉잎만 떼면 속은 깨끗해요.', '괴산 배추마을', '충청북도 괴산', '산으로 둘러싸인 밭에서 김장 배추를 키워요.', 'products/napa-cabbage-scratched.jpg', true, false, true),
  ('napa-cabbage-irregular-1ea', 'napa-cabbage', '모양 제각각 배추 1통', '모양이 반듯하지 않은 배추예요. 썰어서 국이나 볶음에 쓰면 모양은 상관없어요.', 2500, 5500, '1통 (약 2.5kg)', 'irregular', '한쪽으로 기울거나 길쭉하지만 속이 꽉 찼어요.', '해남 땅끝배추', '전라남도 해남', '겨울에도 따뜻한 땅끝에서 배추를 키워요.', 'products/napa-cabbage-irregular.jpg', true, false, true),
  ('paprika-small-1kg', 'paprika', '꼬마 파프리카 1kg', '작아서 규격에서 빠진 파프리카예요. 도시락이나 샐러드에 쓰기 딱 좋아요.', 5900, 9500, '1kg (8~10개)', 'small', '크기가 작아 한 번에 하나씩 쓰기 좋아요.', '영양 파프리카농장', '경상북도 영양', '빨강, 노랑, 주황, 초록 파프리카를 함께 키워요.', 'products/paprika-small.jpg', false, false, true),
  ('paprika-scratched-3ea', 'paprika', '흠집 빨강 파프리카 3입', '표면에 긁힌 자국이 있는 빨강 파프리카예요. 볶음이나 구이에 쓰면 티가 안 나요.', 3500, 5700, '3입', 'scratched', '껍질에 작은 긁힘이 있지만 과육은 두껍고 달아요.', '김제 유리온실', '전라북도 김제', '온실에서 온도를 맞춰 가며 정성껏 키워요.', 'products/paprika-scratched.jpg', false, false, true),
  ('tomato-scratched-2kg', 'tomato', '갈라진 토마토 2kg', '완숙되며 껍질이 갈라진 토마토예요. 소스나 수프로 만들면 맛이 진해요.', 6900, 11800, '2kg', 'scratched', '익으면서 꼭지 주변이 갈라졌어요. 받은 날 바로 드세요.', '부여 토마토하우스', '충청남도 부여', '줄기에서 충분히 익혀 따서 감칠맛이 진해요.', 'products/tomato-scratched.jpg', true, false, true),
  ('tomato-small-1-5kg', 'tomato', '꼬마 토마토 1.5kg', '크기가 작아 규격에서 빠진 토마토예요. 한입에 먹기 좋고 도시락에도 좋아요.', 5500, 8900, '1.5kg', 'small', '일반 토마토보다 작지만 단맛은 더 진해요.', '담양 햇살농장', '전라남도 담양', '햇볕이 잘 드는 비닐하우스에서 토마토를 키워요.', 'products/tomato-small.jpg', true, false, true),
  ('cucumber-scratched-10ea', 'cucumber', '흠집 오이 10입', '겉에 긁힌 자국이 있는 오이를 넉넉히 담았어요. 오이지나 피클 담그기에 좋아요.', 4900, 7900, '10입', 'scratched', '가시 부분이 긁혀 있지만 아삭함은 그대로예요.', '천안 오이농장', '충청남도 천안', '매일 아침 수확해서 바로 보내 드려요.', 'products/cucumber-scratched.jpg', true, false, true),
  ('cucumber-small-7ea', 'cucumber', '짧은 오이 7입', '길이가 짧아 규격에서 빠진 오이예요. 1인 가구가 무침 한 번 하기 딱 좋아요.', 2900, 4900, '7입', 'small', '길이가 짧아 한 번에 다 쓰기 좋아요.', '상주 백오이농원', '경상북도 상주', '물 빠짐이 좋은 밭에서 백오이를 키워요.', 'products/cucumber-small.jpg', true, false, true),
  ('aehobak-small-3ea', 'aehobak', '꼬마 애호박 3입', '크기가 작아 규격에서 빠진 애호박이에요. 전이나 볶음 한 번 하기 딱 좋아요.', 2900, 4800, '3입', 'small', '일반 애호박보다 작아 한 번에 쓰기 좋아요.', '춘천 호박농원', '강원도 춘천', '비닐을 씌워 반듯하게 키우는 대신 자연스럽게 키워요.', 'products/aehobak-small.jpg', true, false, true),
  ('aehobak-bent-2ea', 'aehobak', '휜 애호박 2입', '자라면서 휘어진 애호박이에요. 썰어 쓰면 모양은 전혀 상관없어요.', 2500, 4200, '2입', 'bent', '활처럼 휘었지만 속은 연하고 달아요.', '춘천 호박농원', '강원도 춘천', '비닐을 씌워 반듯하게 키우는 대신 자연스럽게 키워요.', 'products/aehobak-bent.jpg', true, false, true),
  ('aehobak-scratched-3ea', 'aehobak', '흠집 애호박 3입', '바람에 잎과 쓸려 껍질에 흠집이 난 애호박이에요. 된장찌개에 넣어 보세요.', 3200, 5400, '3입', 'scratched', '껍질에 긁힌 자국이 있어요. 맛과 식감은 정상품과 같아요.', '진주 들판농장', '경상남도 진주', '남강 옆 넓은 들판에서 호박과 가지를 키워요.', 'products/aehobak-scratched.jpg', true, false, true),
  ('eggplant-bent-5ea', 'eggplant', '휜 가지 5입', '곧게 자라지 않아 B급이 된 가지예요. 가지볶음이나 가지구이에 좋아요.', 3500, 5900, '5입', 'bent', '구부러졌지만 껍질이 얇고 속이 부드러워요.', '진주 들판농장', '경상남도 진주', '남강 옆 넓은 들판에서 호박과 가지를 키워요.', 'products/eggplant-bent.jpg', true, false, true),
  ('eggplant-scratched-4ea', 'eggplant', '흠집 가지 4입', '표면에 긁힌 자국이 있는 가지예요. 나물이나 튀김으로 즐겨 보세요.', 2900, 4900, '4입', 'scratched', '껍질에 작은 긁힘이 있어요. 익히면 티가 안 나요.', '하동 섬진강농장', '경상남도 하동', '섬진강 바람이 지나는 밭에서 가지를 키워요.', 'products/eggplant-scratched.jpg', true, false, true),
  ('eggplant-small-7ea', 'eggplant', '꼬마 가지 7입', '크기가 작아 선별에서 빠진 가지예요. 반으로 갈라 구워 먹으면 맛있어요.', 3900, 6500, '7입', 'small', '작고 통통해서 통째로 굽기 좋아요.', '하동 섬진강농장', '경상남도 하동', '섬진강 바람이 지나는 밭에서 가지를 키워요.', 'products/eggplant-small.jpg', true, false, true),
  ('sweet-pumpkin-small-3ea', 'sweet-pumpkin', '꼬마 단호박 3통', '크기가 작아 규격에서 빠진 단호박이에요. 통째로 쪄서 간식으로 드세요.', 5900, 9800, '3통', 'small', '주먹보다 조금 큰 크기라 한 통씩 쪄 먹기 좋아요.', '경주 단호박농장', '경상북도 경주', '물 빠짐이 좋은 밭에서 단호박을 덩굴째 키워요.', 'products/danhobak-small.jpg', true, false, true),
  ('sweet-pumpkin-scratched-2ea', 'sweet-pumpkin', '껍질 흠집 단호박 2통', '덩굴 사이에서 껍질이 긁힌 단호박이에요. 껍질을 벗겨 수프로 만들기 좋아요.', 4900, 7900, '2통', 'scratched', '껍질에 긁힌 자국이 있지만 속은 노랗고 달아요.', '경주 단호박농장', '경상북도 경주', '물 빠짐이 좋은 밭에서 단호박을 덩굴째 키워요.', 'products/danhobak-scratched.jpg', true, false, true),
  ('sweet-pumpkin-irregular-2ea', 'sweet-pumpkin', '울퉁불퉁 단호박 2통', '모양이 고르지 않은 단호박이에요. 잘라서 찌거나 구우면 모양은 상관없어요.', 4500, 7900, '2통', 'irregular', '모양이 찌그러졌지만 포슬포슬함은 그대로예요.', '춘천 호박농원', '강원도 춘천', '비닐을 씌워 반듯하게 키우는 대신 자연스럽게 키워요.', 'products/danhobak-irregular.jpg', true, false, true),
  ('shiitake-small-300g', 'shiitake', '꼬마 표고버섯 300g', '갓 크기가 작아 선별에서 빠진 표고버섯이에요. 손질 없이 바로 쓰기 편해요.', 4500, 6900, '300g', 'small', '갓이 작아서 통째로 볶거나 국에 넣기 좋아요.', '장흥 버섯농가', '전라남도 장흥', '참나무 원목에서 버섯을 천천히 키우고 있어요.', 'products/shiitake-small.jpg', false, false, true),
  ('shiitake-scratched-1kg', 'shiitake', '갓 갈라진 표고버섯 1kg', '자라면서 갓이 갈라진 표고버섯이에요. 말려 두면 육수용으로 오래 쓸 수 있어요.', 11900, 18900, '1kg', 'scratched', '갓 표면이 갈라졌지만 향이 더 진하게 올라와요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/shiitake-scratched.jpg', false, false, true),
  ('king-oyster-small-500g', 'king-oyster', '꼬마 새송이버섯 500g', '크기가 작아 선별에서 빠진 새송이버섯이에요. 버터구이나 꼬치로 좋아요.', 2900, 4800, '500g', 'small', '대가 가늘고 짧아 통째로 굽기 좋아요.', '화성 버섯하우스', '경기도 화성', '온도와 습도를 맞춘 재배사에서 새송이를 길러요.', 'products/king-oyster-small.jpg', false, false, true),
  ('king-oyster-bent-500g', 'king-oyster', '휜 새송이버섯 500g', '자라면서 대가 휜 새송이버섯이에요. 결대로 찢어 볶으면 모양은 상관없어요.', 2700, 4800, '500g', 'bent', '대가 휘었지만 쫄깃함은 그대로예요.', '화성 버섯하우스', '경기도 화성', '온도와 습도를 맞춘 재배사에서 새송이를 길러요.', 'products/king-oyster-bent.jpg', false, false, true),
  ('king-oyster-bent-1kg', 'king-oyster', '휜 새송이버섯 1kg', '대가 휘어 B급이 된 새송이를 대용량으로 담았어요. 자주 요리하는 집에 좋아요.', 4900, 8900, '1kg', 'bent', '휜 버섯을 넉넉히 담았어요. 장조림이나 전골에 좋아요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/king-oyster-bent-bulk.jpg', false, false, true),
  ('king-oyster-scratched-500g', 'king-oyster', '갓 상처 새송이버섯 500g', '포장하면서 갓에 상처가 생긴 새송이버섯이에요. 볶음이나 찌개에 넣어 보세요.', 2500, 4800, '500g', 'scratched', '갓 가장자리가 조금 찢어졌어요. 썰어 쓰면 티가 안 나요.', '화성 버섯하우스', '경기도 화성', '온도와 습도를 맞춘 재배사에서 새송이를 길러요.', 'products/king-oyster-scratched.jpg', false, false, true),
  ('king-oyster-irregular-1kg', 'king-oyster', '굵기 제각각 새송이버섯 1kg', '굵기가 고르지 않은 새송이버섯이에요. 썰어서 쓰면 모양은 상관없어요.', 4500, 8900, '1kg', 'irregular', '굵기와 길이가 섞여 있어요. 굵은 건 구이, 얇은 건 볶음으로 써요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/king-oyster-irregular.jpg', false, false, true),
  ('apple-irregular-2kg', 'apple', '모양 제각각 사과 2kg', '모양이 고르지 않아 선물 상자에서 빠진 사과예요. 깎아 먹거나 주스로 좋아요.', 11900, 17800, '2kg (6~8개)', 'irregular', '한쪽이 찌그러지거나 길쭉하지만 아삭함은 그대로예요.', '영주 사과마을', '경상북도 영주', '소백산 아래 일교차가 큰 곳에서 키웠어요.', 'products/apple-irregular.jpg', true, false, true),
  ('mandarin-small-3kg', 'mandarin', '꼬마 귤 3kg', '크기가 작아 선별에서 빠진 귤이에요. 한입에 쏙 들어가서 아이들 간식으로 좋아요.', 8900, 14900, '3kg', 'small', '알이 작아 껍질이 얇고 더 달아요.', '서귀포 감귤원', '제주특별자치도 서귀포', '한라산 남쪽 따뜻한 비탈에서 귤을 키워요.', 'products/mandarin-small.jpg', true, false, true),
  ('mandarin-scratched-5kg', 'mandarin', '껍질 흠집 귤 5kg', '껍질에 흠집이 있어 B급이 된 귤이에요. 까서 먹으면 정상품과 똑같아요.', 12900, 21900, '5kg', 'scratched', '바람에 가지와 쓸려 껍질에 자국이 있어요. 속은 멀쩡해요.', '서귀포 감귤원', '제주특별자치도 서귀포', '한라산 남쪽 따뜻한 비탈에서 귤을 키워요.', 'products/mandarin-scratched.jpg', true, false, true),
  ('mandarin-irregular-3kg', 'mandarin', '모양 제각각 귤 3kg', '크기와 모양이 고르지 않은 귤이에요. 귤청이나 주스로 만들기에도 좋아요.', 9900, 15900, '3kg', 'irregular', '크기와 모양이 섞여 있지만 새콤달콤해요.', '제주 한림밭', '제주특별자치도 한림', '바닷바람을 맞고 자라 잎이 두툼해요.', 'products/mandarin-irregular.jpg', true, false, true),
  ('green-onion-bent-1bunch', 'green-onion', '휜 대파 1단', '자라면서 줄기가 휜 대파예요. 썰어서 쓰면 모양은 상관없어요.', 1900, 3200, '1단', 'bent', '줄기가 휘었지만 향과 단맛은 그대로예요.', '진도 대파밭', '전라남도 진도', '겨울 바닷바람을 맞고 자라 단맛이 나요.', 'products/green-onion-bent.jpg', false, false, true),
  ('green-onion-irregular-2bunch', 'green-onion', '굵기 제각각 대파 2단', '굵기가 고르지 않아 선별에서 빠진 대파예요. 썰어서 냉동해 두면 편해요.', 3500, 5900, '2단', 'irregular', '굵기가 섞여 있어요. 굵은 건 국, 가는 건 양념으로 써요.', '진도 대파밭', '전라남도 진도', '겨울 바닷바람을 맞고 자라 단맛이 나요.', 'products/green-onion-irregular.jpg', false, false, true),
  ('green-onion-scratched-1bunch', 'green-onion', '잎끝 마른 대파 1단', '잎 끝이 마른 대파예요. 흰 부분은 단단하고 향이 진해요.', 1700, 3200, '1단', 'scratched', '초록 잎 끝이 조금 말랐어요. 끝만 자르면 돼요.', '진도 대파밭', '전라남도 진도', '겨울 바닷바람을 맞고 자라 단맛이 나요.', 'products/green-onion-scratched.jpg', false, false, true),
  ('chili-small-300g', 'chili', '짧은 풋고추 300g', '길이가 짧아 규격에서 빠진 풋고추예요. 된장찌개나 쌈에 좋아요.', 2500, 3900, '300g', 'small', '길이가 짧아 통째로 쌈장에 찍어 먹기 좋아요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/chili-small.jpg', true, false, true),
  ('chili-bent-500g', 'chili', '꼬부랑 홍고추 500g', '많이 휘어서 B급이 된 홍고추예요. 썰어서 양념이나 고명으로 쓰세요.', 3900, 6500, '500g', 'bent', '꼬불꼬불 휘었지만 색이 진하고 매콤해요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/chili-bent.jpg', true, false, true),
  ('chili-scratched-500g', 'chili', '흠집 청양고추 500g', '따면서 흠집이 생긴 청양고추예요. 찌개나 볶음에 넣으면 칼칼해요.', 3500, 5900, '500g', 'scratched', '껍질에 작은 흠집이 있어요. 썰어 쓰면 티가 안 나요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/chili-scratched.jpg', true, false, true),
  ('chili-irregular-500g', 'chili', '크기 제각각 고추 500g', '크기와 색이 고르지 않은 고추를 섞어 담았어요. 고추장아찌로 만들어 보세요.', 2900, 4900, '500g', 'irregular', '크기와 색이 섞여 있어요. 장아찌를 담그기 좋아요.', '청양 고추농가', '충청남도 청양', '맵기로 이름난 청양에서 고추와 버섯을 키워요.', 'products/chili-irregular.jpg', true, false, true)
on conflict (id) do update set
  vegetable_id = excluded.vegetable_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  original_price = excluded.original_price,
  unit = excluded.unit,
  ugly_reason = excluded.ugly_reason,
  condition_note = excluded.condition_note,
  farm_name = excluded.farm_name,
  farm_region = excluded.farm_region,
  farm_story = excluded.farm_story,
  image_path = excluded.image_path,
  is_seasonal = excluded.is_seasonal,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active;

commit;
